import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { extractSets, generateCombinations, VennDiagram } from '@upsetjs/react';
 import React,{useMemo} from 'react';





function GettingStarted() {
const elems = useMemo(
    () => [
      { name: 'A', sets: ['S1', 'S2'] },
      { name: 'B', sets: ['S1'] },
      { name: 'C', sets: ['S2'] },
      { name: 'D', sets: ['S3'] },
    ],
    []
  );
  
  const sets = useMemo(() => extractSets(elems), [elems]);
const combinations = useMemo(() => generateCombinations(sets), [sets]);
  const [selection, setSelection] = React.useState(null);
  return (
    <VennDiagram
      sets={sets}
      combinations={combinations}
      width={1000}
      height={700}
      selection={selection}
      onHover={setSelection}
      background={'white'}
    />
  );
}


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Next.js!</a>
        </h1>
        <GettingStarted />
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
